## Erfa user login
POST http://http://localhost:5000//erfa/login HTTP/1.1
Content-Type: application/json

{

    "username": "Muskaan",
    "password":"abc.124"

}


### erfa admin login request
POST http://http://localhost:5000//erfa/login HTTP/1.1
Content-Type: application/json

{

    "": "head",
    "password":"abc.123"

}
### new user in erfa
POST http://http://localhost:5000//erfa/signup HTTP/1.1
Content-Type: application/json

{

    "username": "elliott",
    "password":"abc.123",
    "usertype": "officer"

}

### student sign up request
POST http://http://localhost:5000//student/signup HTTP/1.1
Content-Type: application/json

{
        "regid": "1812134",
        "password": "abc.123",
        "name":"Rani Imam",
        "program": "BSCS",
        "section": "7A",
        "cellnumber": "03747921563",
        "email": "rustafa@gmail.com",
        "dob": "10-12-1998",
        "permanentaddress": "B-201,North Karachi, Karachi",
        "mailingaddress":"B-201,North Karachi, Karachi",
        "fathername": "Haider"
}

### student login request
POST http://http://localhost:5000//student/login HTTP/1.1
Content-Type: application/json

{
    "regid":"1812114",
    "password":"abc.123"
}

#### student login request

POST http://http://localhost:5000//student/login HTTP/1.1
Content-Type: application/json

{
    "regid":"1812134",
    "password":"abc.123"

}

#### panlist login request for
POST http://http://localhost:5000//panelist/login HTTP/1.1
Content-Type: application/json

{
    "name":" "
}




### student login request
GET  http://http://localhost:5000//student/getallstudents HTTP/1.1
Content-Type: application/json

{

}